// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PaymentApi.Models
{
    [Index("ClaimID", Name = "IX_ClaimTransactions_ClaimID")]
    public partial class ClaimTransactions
    {
        [Key]
        public int ClaimTransactionID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        public int ClaimID { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string ClaimTransType { get; set; }
        [Column(TypeName = "money")]
        public decimal Amount { get; set; }
        [Column(TypeName = "money")]
        public decimal ReserveBalance { get; set; }

        [ForeignKey("ClaimID")]
        [InverseProperty("ClaimTransactions")]
        public virtual Claims Claim { get; set; }
    }
}