// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PaymentApi.Models
{
    public partial class SutContext : DbContext
    {
        public SutContext()
        {
        }

        public SutContext(DbContextOptions<SutContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ClaimTransactions> ClaimTransactions { get; set; }
        public virtual DbSet<Claims> Claims { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ClaimTransactions>(entity =>
            {
                entity.HasKey(e => e.ClaimTransactionID)
                    .HasName("PK__ClaimTra__2F9489E28741F66B");

                entity.Property(e => e.ClaimTransType).IsFixedLength();

                entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ReserveBalance).HasDefaultValueSql("((0.00))");

                entity.HasOne(d => d.Claim)
                    .WithMany(p => p.ClaimTransactions)
                    .HasForeignKey(d => d.ClaimID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ClaimTransactions_Claims");
            });

            modelBuilder.Entity<Claims>(entity =>
            {
                entity.HasKey(e => e.ClaimID)
                    .HasName("PK__Claims__EF2E13BB45BCF81A");

                entity.Property(e => e.IsLocked).HasDefaultValueSql("((0))");

                entity.Property(e => e.Token)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}