// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ClaimTransWorker.Models
{
    public partial class sutContext : DbContext
    {
        public sutContext()
        {
        }

        public sutContext(DbContextOptions<sutContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ClaimTransactions> ClaimTransactions { get; set; }
        public virtual DbSet<Claims> Claims { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
               optionsBuilder.UseSqlServer("Data Source=nixnas;Initial Catalog=sut;Persist Security Info=True;User ID=sa;Password=Cession01@@@");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ClaimTransactions>(entity =>
            {
                entity.HasKey(e => e.ClaimTransactionID)
                    .HasName("PK__ClaimTra__2F9489E20F9A0445");

                entity.Property(e => e.ClaimTransType).IsFixedLength();

                entity.HasOne(d => d.Claim)
                    .WithMany(p => p.ClaimTransactions)
                    .HasForeignKey(d => d.ClaimID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ClaimTransactions_Claims");
            });

            modelBuilder.Entity<Claims>(entity =>
            {
                entity.HasKey(e => e.ClaimID)
                    .HasName("PK__Claims__EF2E13BBB4AD42E1");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}